### ISSUE TITLE
postgis support

### ISSUE THREAD

**Issue by giszh86** [anyways-open/NetTopologySuite.IO.VectorTiles#16]
Is it possible to create tiles with postgis?

**Comment by xivk** [comment]
You should be able to combine this package with this one:

https://github.com/NetTopologySuite/NetTopologySuite.IO.PostGis

Read features from Postgis and write them using this package. But, there are probably better alternatives serving vector tiles with postgis.

**Comment by giszh86** [comment]
Which alternatives is the better? I'm looking for this one.

**Comment by xivk** [comment]
https://info.crunchydata.com/blog/dynamic-vector-tiles-from-postgis

**Comment by giszh86** [comment]
thanks
