### ISSUE TITLE
Add support for writing all representable geometry types to a vector tile

### ISSUE THREAD

**Issue by FObermaier** [anyways-open/NetTopologySuite.IO.VectorTiles#6]
According to the [specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#434-geometry-types) has support for all basic OGC geometry types but GeometryCollection.
The `MapboxTileWriter` currently only has support for
- [x] Point
- [x] LineString
- [x] Polygon
- [x] MultiPoint
- [x] MultiLineString
- [x] MultiPolygon

**Comment by xivk** [comment]
This looks like it's done!
