### ISSUE TITLE
Lots of questions...

### ISSUE THREAD

**Issue by robalexclark** [anyways-open/NetTopologySuite.IO.VectorTiles#9]
Well this looks great! I've been looking for something to generate tiles from WKT using c# for ages! 

A few questions though
1) Can you upgrade the project to use the latest version of NTS. At the moment its built against 1.15 but could you move it to 2 as the IGeometry namespaces have changed:
https://stackoverflow.com/questions/50767900/nettopologysuite-and-dotspatial-wktreader

2) Is it possible to generate raster tiles from this?

**Comment by xivk** [comment]
The update toe NTS 2 was just done.

As for generating raster tiles: no that cannot be done, generating vector tiles is relatively easy compared to rendering raster tiles.
